server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: customer
#          Without using discovery server
#          uri: http://localhost:8080
#          Using discovery server
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
